Migrate project to TypeScript
VahidNaderi/googlerankchecker pull request #14
Opened 2023-08-16 08:27 UTC by ndramir

- Install TypeScript as a dev dependency and add
  tsconfig.json file.
- Rename all .js files to .ts and fix any type errors.
- Add Webpack config to use ts-loader for .ts files and
  sass-loader for .scss files.
- Refactor project structure to follow TypeScript best
  practices.

2023-08-18 12:21 UTC, VahidNaderi requested changes
Thank you for your significant contribution, that's awesome. But can you please consider my comments and resolve them?

2023-08-18 12:21 UTC, VahidNaderi commented on src/helpers/storage-helper.ts
I'm not ok with this one being named StorageHelper It can be StorageWrapper or GrcStorage or something else but being a helper is not suit this one.  And it's methods should not be static it's opposed to OOP.

2023-08-18 12:21 UTC, VahidNaderi commented on src/popup/popup.ts
What's that "Check" comment about?!

2023-08-18 12:21 UTC, VahidNaderi commented on src/popup/popup.ts
Can we use async/await for promises to make the code more readable?

2023-08-22 12:37 UTC, ndramir commented on src/helpers/storage-helper.ts
You are right. I defined it as a service and named it StorageService. The methods should not be static because static methods belong to the class, not the object. This means that they cannot access the instance variables or methods of the object, which are essential for encapsulation and abstraction.

2023-08-22 12:40 UTC, ndramir commented on src/popup/popup.ts
The check comment was for this part of the code: new URL(tabs[0].url!). This is because the tabs[0].url property can be undefined if the tab is not fully loaded or has no URL. The ! operator asserts that it is not undefined, but this can cause a runtime error if it is. The new URL() constructor validates the URL and throws an error if it is invalid. This way, we can catch the error and handle it gracefully. And yes, I used async/await in the new commit to make the code more readable.

2023-10-02 06:44 UTC, VahidNaderi approved these changes
Awesome work!

2023-10-02 06:44 UTC, merged